# Form implementation generated from reading ui file 'dlgDatos.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgExportarDatos(object):
    def setupUi(self, dlgExportarDatos):
        dlgExportarDatos.setObjectName("dlgExportarDatos")
        dlgExportarDatos.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        dlgExportarDatos.resize(400, 300)
        self.lblElegirDatos = QtWidgets.QLabel(dlgExportarDatos)
        self.lblElegirDatos.setGeometry(QtCore.QRect(80, 130, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblElegirDatos.setFont(font)
        self.lblElegirDatos.setObjectName("lblElegirDatos")
        self.chkClientes = QtWidgets.QCheckBox(dlgExportarDatos)
        self.chkClientes.setGeometry(QtCore.QRect(90, 190, 70, 17))
        self.chkClientes.setObjectName("chkClientes")
        self.buttonGroup = QtWidgets.QButtonGroup(dlgExportarDatos)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.chkClientes)
        self.chkCoches = QtWidgets.QCheckBox(dlgExportarDatos)
        self.chkCoches.setGeometry(QtCore.QRect(230, 190, 70, 17))
        self.chkCoches.setObjectName("chkCoches")
        self.buttonGroup.addButton(self.chkCoches)
        self.label = QtWidgets.QLabel(dlgExportarDatos)
        self.label.setGeometry(QtCore.QRect(150, 30, 81, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/help-web-button.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.btnExportarDatos = QtWidgets.QPushButton(dlgExportarDatos)
        self.btnExportarDatos.setGeometry(QtCore.QRect(150, 230, 75, 23))
        self.btnExportarDatos.setObjectName("btnExportarDatos")

        self.retranslateUi(dlgExportarDatos)
        QtCore.QMetaObject.connectSlotsByName(dlgExportarDatos)

    def retranslateUi(self, dlgExportarDatos):
        _translate = QtCore.QCoreApplication.translate
        dlgExportarDatos.setWindowTitle(_translate("dlgExportarDatos", "Exportar Datos"))
        self.lblElegirDatos.setText(_translate("dlgExportarDatos", "Elija los datos que desea Exportar"))
        self.chkClientes.setText(_translate("dlgExportarDatos", "Clientes"))
        self.chkCoches.setText(_translate("dlgExportarDatos", "Coches"))
        self.btnExportarDatos.setText(_translate("dlgExportarDatos", "Aceptar"))
