# Form implementation generated from reading ui file 'dlgSalir.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(280, 220)
        Dialog.setMinimumSize(QtCore.QSize(280, 220))
        Dialog.setMaximumSize(QtCore.QSize(280, 220))
        Dialog.setModal(True)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 100, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 10, 60, 60))
        self.label_2.setMinimumSize(QtCore.QSize(60, 60))
        self.label_2.setMaximumSize(QtCore.QSize(60, 60))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("img/imagenadvertida.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.btnCancelar = QtWidgets.QPushButton(Dialog)
        self.btnCancelar.setGeometry(QtCore.QRect(170, 150, 70, 20))
        self.btnCancelar.setMinimumSize(QtCore.QSize(70, 20))
        self.btnCancelar.setMaximumSize(QtCore.QSize(70, 20))
        self.btnCancelar.setObjectName("btnCancelar")
        self.btnSalir = QtWidgets.QPushButton(Dialog)
        self.btnSalir.setGeometry(QtCore.QRect(40, 150, 70, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.btnSalir.sizePolicy().hasHeightForWidth())
        self.btnSalir.setSizePolicy(sizePolicy)
        self.btnSalir.setMinimumSize(QtCore.QSize(70, 20))
        self.btnSalir.setMaximumSize(QtCore.QSize(70, 20))
        self.btnSalir.setObjectName("btnSalir")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Estas seguro que deseas salri de la aplicacion"))
        self.btnCancelar.setText(_translate("Dialog", "Cancelar"))
        self.btnSalir.setText(_translate("Dialog", "Salir"))
